[package]
name = "auxmos"
version = "0.1.0"
authors = ["Putnam <putnam3145@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
monstermos = []
explosive_decompression = ["monstermos"]

[lib]
crate-type = ["cdylib"]

[dependencies]
dm = { path = "../dm" }
sigscan = { path = "../sigscan" }
turf_grid = { path = "../turf_grid" }
lazy_static = "1.4.0"
sprs = "0.9.2"
itertools = "0.9.0"
dashmap = "3.11.10"
smallvec = "1.4.2"
rayon = "1.5.0"
float-ord = "0.2.0"
crossbeam = "0.8.0"
flume = "0.9.1"
coarsetime = "0.1.16"
