[package]
name = "atmospherics"
version = "0.1.0"
authors = ["Putnam <putnam3145@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dm = { path = "../dm" }
sigscan = { path = "../sigscan" }
turf_grid = { path = "../turf_grid" }
lazy_static = "1.4.0"
sprs = "0.9.2"
itertools = "0.9.0"
