name: Generate Docs

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false # Necessary.

    - name: Cache Cargo
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-docs-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-docs-cargo-

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable-i686-unknown-linux-gnu
        target: i686-unknown-linux-gnu
        override: true

    - name: Install Dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt install libc6-i386
        sudo apt install libstdc++6:i386
        sudo apt install build-essential g++-multilib
        sudo apt install pkg-config:i386 libssl-dev:i386

    - name: Build Docs
      run: cargo doc --no-deps

    - name: Deploy 🚀
      if: ${{ github.event_name == 'push' }} # Only deploy if we actually push to a branch
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: docs        # The branch the action should deploy to.
        FOLDER: target/doc  # The folder we deploy to Github Sites.
        CLEAN: true         # Automatically remove deleted files from the deploy branch.
        SINGLE_COMMIT: true # Keep only one commit for the docs branch.
        CLEAN_EXCLUDE: '["/index.html"]' # Exclude the index from being deleted, since it's not generated. https://github.com/rust-lang/rust/issues/73185
